# Generated by Django 5.1.5 on 2025-01-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ('-created_at',)},
        ),
    ]
