# Generated by Django 5.1.5 on 2025-02-04 09:16

import django.db.models.deletion
import myBlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myBlog.models.get_file_path)),
                ('descriptions', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to=myBlog.models.get_file_path)),
                ('small_description', models.CharField(max_length=250)),
                ('descriptions', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBlog.category')),
            ],
        ),
    ]
