# Generated by Django 5.1.5 on 2025-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_contact_email_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Travel', 'Travel'), ('Food', 'Food'), ('Blog Tips', 'Blog Tips'), ('SEO Optimization', 'SEO Optimization')], max_length=200),
        ),
    ]
