# Generated by Django 5.1.5 on 2025-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0005_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Travel', 'Travel Blogs'), ('Food', 'Food'), ('Blog Tips', 'Blog Tips'), ('SEO Optimization', 'SEO Optimization')], default='Travel Blogs', max_length=200),
        ),
    ]
